## Its Starts with a Tensor 

In DL tensors refers to the generalization of vectors and matrices to an abitrary number of dimenensions. Another name for tensor is a multidimensional array.  The dimensionality of a tensor coincides with the number of indexes used to refere to scalar values within the tensor.  

Scalar -> 0D 
Vector -> 1D 
Matrix -> 2D 
tensor -> 3D. 

A tensor can also be defined as an array: that data structure that sores a collection of numbers that are accessible individually using an index and that can indexed with mutiple indices. 



In [1]:

%cd ..


# from list to tensor 
a = [1.0, 2.0, 1.0] 
print(a)
print([0])

a [2] = 3.0
print(a)

/home/emilextrig/workspace/code4all
[1.0, 2.0, 1.0]
[0]
[1.0, 2.0, 3.0]


In [2]:
# first tensor 
import torch 

a= torch.ones(3) 
print(a)

print(a[1])

print(float(a[1])) # conveerting from torch to float. 

a[2] = 2.0 
print(a)

tensor([1., 1., 1.])
tensor(1.)
1.0
tensor([1., 1., 2.])


In [3]:
# 1D tensor by storing Xs in the even indicies and Ys in the odd indicies 
points = torch.zeros(6) 
points[0] = 4.0 
points[1] = 1.0
points[2] = 5.0 
points[3] = 3.0 
points[4] = 2.0 
points[5] = 1.0 
print(points)

tensor([4., 1., 5., 3., 2., 1.])


In [4]:
# we can also pass a list to a constructor to have the same effect. 
points = torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
print(points)

tensor([4., 1., 5., 3., 2., 1.])


In [5]:
# to get coordinates of the first point, we do the following:
print(float(points[0]), float(points[1]))

4.0 1.0


In [6]:
# creating a 2D tensor 
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
print(points)
print("\n", points.shape)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

 torch.Size([3, 2])


In [7]:
#using zeros and ones to initialize the tensor, providing the size as a tuple 
points = torch.zeros(3,2) 
print(points)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [8]:
# using indices to access tensors 
points = torch.tensor([[4.0, 1.0],[5.0,3.0],[2.0, 1.0]])
print(points)
print("\n", "indexing (1,0) ", "\n", points[0,1])

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

 indexing (1,0)  
 tensor(1.)


In [9]:
# This returns the Y cord of the 0th point in our dataset.  
print(points[0])

tensor([4., 1.])


#### Indexing tensors 

In [10]:
print(points[1:])

print("\n", points[1:,:])

print("\n", points[1:,0])

print("\n", points[None]) # adds a dimension of size 1, just like unsqueenze 

tensor([[5., 3.],
        [2., 1.]])

 tensor([[5., 3.],
        [2., 1.]])

tensor([5., 2.])

 tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


#### Named Tensor 
The dimension (or axes) of tensor are usually index something like pixel location so or color channles. This means when we want to index into a tensor, we need to remember the ordering of the dimensions and write our indexing accordingly. As data is transformed thorugh multiple tensors, keeping track of which dimension contains what data can be error-prone. 

In [11]:
# eg of the statment above 
img_t = torch.randn(3,5,5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

print(img_t)
print("\n", weights)

SyntaxError: invalid syntax (<ipython-input-11-e7f99f9d24f6>, line 2)

In [12]:
# often times we want to generalize, for eg. from grayscal 2D tensor image with height and width dimension to color image with 3D channel as in RGB or from a single image to a batch of images. 

batch_t = torch.randn(2,3,5,5)  # shape [batch, channels, rows, columns]
print(batch_t)

tensor([[[[-0.8398,  1.8165,  0.4064,  1.1685, -0.2680],
          [-2.0672,  0.8045, -1.3468,  1.1119, -1.8951],
          [-0.5332,  0.9842, -0.9437, -0.8297,  1.9160],
          [ 2.0031,  0.3015,  0.8465, -0.5757,  1.3212],
          [-0.0958, -1.3644,  0.4791, -0.8783,  0.7029]],

         [[ 0.1853,  1.9100,  0.7568, -1.0296, -0.9602],
          [ 0.2344, -1.0092, -0.7116, -0.3713, -0.2573],
          [ 0.6307,  2.6009,  0.1683,  2.0050, -0.7501],
          [ 0.3550,  2.9700,  1.4534,  0.0515,  0.7944],
          [-0.0125, -0.7789, -1.1048, -0.1398,  0.6653]],

         [[ 0.1667,  0.1875, -0.3679, -1.2121, -0.4320],
          [ 0.6433,  0.3409, -0.4817,  0.6761, -0.3194],
          [-2.2736,  0.0697,  0.2462,  0.7144, -0.7994],
          [ 0.8667, -0.6244, -0.3760,  1.6183, -1.6230],
          [ 0.4188,  0.8149,  0.7196,  0.0696, -0.2707]]],


        [[[ 0.9666,  0.8738, -0.6900,  1.8916, -0.0542],
          [-0.0545, -0.1494,  0.2354, -0.7871, -0.0344],
          [-0.7540,  0.

In [13]:
# sometimes the RGB channels are in dimension 0, and sometimes they are in dimension 1. But we can generalize by counting from the end: they are always in dimension -3, the third from the end.  

img_gray_naive = img_t.mean(-3) 
batch_gray_naive = batch_t.mean(-3) 

print(img_gray_naive)
print("\n", batch_gray_naive)

print("\n", img_gray_naive.shape, batch_gray_naive.shape)

NameError: name 'img_t' is not defined

In [14]:
# multiplying things 
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1) 

img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)

img_gray_weighted = img_weights.sum(-3) 
batch_gray_weighted = batch_weights.sum(-3) 

print(batch_weights.shape, batch_t.shape, unsqueezed_weights.shape)

NameError: name 'weights' is not defined

In [15]:
# using torch einsum for indexing mini-language giving index names to dimensions from sum of such products. 
img_gray_weighted_fancy = torch.einsum('...chw, c->...hw', img_t, weights) 
batch_gray_weighted_fancy = torch.einsum('...chw, c->...hw', batch_t, weights) 
print(batch_gray_weighted_fancy.shape)

NameError: name 'img_t' is not defined

In [16]:
# named tensors feature 
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
print(weights_named)

tensor([0.2126, 0.7152, 0.0722], names=('channels',))


In [17]:
# add names to already existing tensor, we call the refine_names method. 
img_named = img_t.refine_names(..., 'channels','rows','columns') # ellipsis (...) allows you to leave out any number of dimensions
batch_named = batch_t.refine_names(..., 'channels','rows','columns')
print("img named: ", img_named.shape, img_named.names)
print("batch named: ", batch_named.shape, batch_named.names)

NameError: name 'img_t' is not defined

In [18]:
# the method align_as returns a tensor with missing dimensions added and existing ones permuted to the right other
weights_aligned = weights_named.align_as(img_named)
print(weights_aligned.shape, weights_aligned.names)

NameError: name 'img_named' is not defined

In [19]:
#using dimension argument to sum. 
gray_named = (img_named * weights_aligned).sum('channels')
print(gray_named.shape, gray_named.names)


NameError: name 'img_named' is not defined

In [20]:
# combining different elements results to an error 
gray_named = (img_named[..., :3] * weights_named).sum('channel')

NameError: name 'img_named' is not defined

In [21]:
# if we want use tensor outside function that operate on named tensors, we need to drop the names by renaming them to None.  
gray_plain = gray_named.rename(None) 
print(gray_plain.shape, gray_plain.names)

NameError: name 'gray_named' is not defined

### Tensor elements types

#### Specifying the numeric type with dtype
The ```dtype``` argurment to tensor constructors specifies the numerical data (d) type that will be contained in the tensor. 
The data data type specifies the possibile value the tensor can hold (integers vs point numbers) and the number of bytes per value.  The dtype arg. is deliberately similar to the standard numpy arg. of the same name.   List below 
* torch.float32 or torch.float: 32-bit floating-point 
* torch.float64 or torch.double: 64-bit, double-precision floating-point 
* torch.float16 or torch.half: 16-bit, half-precision floating-point 
* torch.int8: signed 8-bit integers 
* torch.uint8: unsigned 8-bit integers
* torch.int16 or torch.short: signed 16-bit integers
* torch.int32 or torch.int: signed 32-bit integers 
* torch.int64 or torch.long: signed 64-bit integers 
* torch.bool: Boolean 

The default data type for tenosrs is 32-bits floating-point. 

#### dtype for every occasion 
Typical NN are executed with 32-bits floating point precision. Higher precision, like 64 bits does not improve models accuracy and cost more memory and computationtime. 16-bit floating point are not present in standard CPU but are avaiable in GPU, which help decrease the footprint of a neural network if needed with minor impact on accuracy. 

Tensors can be used a indexes in other tensors, in which pytorch expects indexing tensors to have 64-bit interger data type. Creating a tensor with integers as arguments such as using ```torch.tensor([2,2])``` will create a 64-bit tensor by default. 

#### Managing a tensor's dtype attributes
eg. below 


In [22]:
import torch 
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1,2],[3,4]], dtype=torch.short) 
print(short_points.dtype)

torch.int16


In [23]:
# we can also cast the output tensor using the corresponding casting method. 
double_points = torch.zeros(10,2).double() 
short_points = torch.ones(10,2).short()

#or a using the to method
double_points = torch.zeros(10,2).to(torch.double) 
short_points = torch.ones(10,2).to(dtype=torch.short)

In [24]:
# when mixing input types in operations, the inputs are converted to the larger type automatically. Thus, if we want 32-bit computation, we need to make sure all inputs are 32-bits

points_64 = torch.rand(5, dtype=torch.double) 
points_short = points_64.to(torch.short) 

print(points_64*points_short) # works from Pytorch 1.3 onwards 

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)


#### The tensor API 
The vast majority of operations on and between tensors are available in the `torch` module and can be called as methods of a tensor object. 
eg below 


In [25]:
#from the torch module 
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1) 
print(a.shape, a_t.shape)


# a method of a tensor 
a = torch.ones(3,2) 
a_t = a.transpose(0,1) 
print(a.shape, a_t.shape)

torch.Size([3, 2]) torch.Size([2, 3])
torch.Size([3, 2]) torch.Size([2, 3])


In [26]:
# Indexing into storage 
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [27]:
points_storage = points.storage()
print(points_storage[0],points.storage()[1]) # we can index a storage of a 2D indicies, since the layout of a storage is always 1D, regardless of the dimensionaluty of any and all the tensor being refered to. 


4.0 1.0


In [28]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points_storage = points.storage() 
points_storage[0] = 2.0 # we change the storage which leads to change in it contents 

points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [29]:
# modifying stored values: in-place operations 
# Trailing underscore to some tensor operation indicate that the method operation should be in place. For eg. zero_. 
a = torch.ones(3,2) 

print(a) 

a.zero_() 

print(a)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [30]:
# Tensor metadata: Size, offset, and stride. 

# In order to index into a storage, tensor rely on size, offset and stride. 
# The size or shape is a tuple indicating how many elements across each dimension the tensor represents. 
# The storage offset is the index in the storage corresponding to the first element in the tensor.
# The stride is the number of elements in the storage that need to be skipped over to obtain the next element along each dimension.


points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]) 
second_point = points[1] 
print("Offset: ", second_point.storage_offset()) # index in the second_point.storage correspond first element of second_point 
print("Size: ",second_point.size()) 
print("Shape: ",second_point.shape)
print("Stride", points.stride())


Offset:  2
Size:  torch.Size([2])
Shape:  torch.Size([2])
Stride (2, 1)


In [31]:
print("Size", second_point.size())
print("Offset", second_point.storage_offset())
print("Stride", second_point.stride()) 


Size torch.Size([2])
Offset 2
Stride (1,)


In [32]:
points = torch.tensor([[4.0, 1.0],[5.0, 3.0], [2.0, 1.0]]) 
second_point = points[1] 
second_point[0] = 10.0 #changing the value in a subtensor affects the main tensor 
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [33]:
points = torch.tensor([[4.0, 1.0],[5.0, 3.0], [2.0, 1.0]]) 
second_point = points[1].clone() # cloning subtensor into a new tensor 
second_point[0] = 10.0 
points # as can be seen second point did not change . 


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [34]:
# Transposing wthout copying 
points = torch.tensor([[4.0, 1.0],[5.0, 3.0], [2.0, 1.0]]) 
print(points, "\n")
points_t = points.t() 
points_t

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]]) 



tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [35]:
# checking if the ids of both objects are the same, as you can see they share the same storage 
print(id(points.storage()) == id(points_t.storage()),"\n")
print(points.stride())
print(points_t.stride())


True 

(2, 1)
(1, 2)


In [36]:
# tranposing in higher dimensions 
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2) 
print(some_t.shape) 
print(transpose_t.shape)

torch.Size([3, 4, 5])
torch.Size([5, 4, 3])


In [37]:
print(some_t.stride())
print(transpose_t.stride())

(20, 5, 1)
(1, 5, 20)


#### Contiguous Tensors 
A tenosrs whose values are laid out in the storage starting fromt he rightmost dimension onward (ie, moving along rows from a 2D tenosr). Contiguous tensors are convenient because we can visit them efficiently in ord without jumpoing around in the storage. Some tensor operations in PyTorch only works on contiguous tensors, such as view.  

In [38]:
print(points.is_contiguous())
print(points_t.is_contiguous())

True
False


In [39]:

print("Stride for non-contiguous tensor", points_t.stride(), "\n") 
points_t_cont = points_t.contiguous() # changing a non contiguous tensor to contiguous tensor 
print("Stride for contiguous tensor", points_t_cont.stride()) 

# once we change from non-continguous tensor to contiguous tensor, then the stride wil change. 

Stride for non-contiguous tensor (1, 2) 

Stride for contiguous tensor (3, 1)


In [40]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [41]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [42]:
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [43]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [44]:
# Numpy Interoperability 

# To get numpy array of our points tensor 
points = torch.ones(3,4) 
points_np = points.numpy() 
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [45]:
# obtaining tensor from numpy array 
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
# Serializing tensors 
"""
Pytorch uses pickle under the hood to seriaize tensor object plus a dedicated serialization code for the storage """

#saving the tensor points to an savpoints.t file 

torch.save(points, "data/savpoints.t")

# or alternative 
with open("data/savpoints.t","wb") as f:
    torch.save(points, f)


FileNotFoundError: [Errno 2] No such file or directory: 'data/savpoints.t'

In [47]:
# loading back file 
points = torch.load("data/savpoints.t")

#or alternative 
with open("data/savpoints.t", "rb") as f:
    point = torch.load(f) 

FileNotFoundError: [Errno 2] No such file or directory: 'data/savpoints.t'

In [48]:
# serializing to HDF5 with h5py 
import h5py 

f = h5py.File("data/ourpoints.hdf5","w") 
dset = f.create_dataset("coords", data=points.numpy()) #coords is a key into the HDF4 file 
f.close()

OSError: Unable to create file (unable to open file: name = 'data/ourpoints.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)

In [49]:
# loading lasat two points into our dataset 
f = h5py.File("data/ourpoints.hdf5","r") 
dset = f["coords"] 
last_point = dset[-2:]
last_point


OSError: Unable to open file (unable to open file: name = 'data/ourpoints.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [50]:
last_points = torch.from_numpy(dset[-2:]) # with this case data is copied over to tensor storage. 

NameError: name 'dset' is not defined

In [51]:
points.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)